/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingSortColumn = IDL.Variant({
  'customerPrincipal' : IDL.Null,
  'tailorName' : IDL.Null,
  'bookingDate' : IDL.Null,
});
export const BookingSortDirection = IDL.Variant({
  'asc' : IDL.Null,
  'desc' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : Id,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'customer' : IDL.Principal,
  'estimatedPrice' : IDL.Opt(IDL.Nat),
  'tailor' : IDL.Opt(IDL.Principal),
  'address' : IDL.Text,
  'dateTime' : IDL.Int,
});
export const TailorProfile = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const BookingHistory = IDL.Record({
  'bookingId' : Id,
  'statusLog' : IDL.Vec(IDL.Tuple(BookingStatus, IDL.Int)),
});
export const SavedAddress = IDL.Record({
  'id' : Id,
  'owner' : IDL.Principal,
  'addressLabel' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBooking' : IDL.Func([Id], [], []),
  'adminActivateTailor' : IDL.Func([Id], [], []),
  'adminAssignTailorToBooking' : IDL.Func([Id, Id], [], []),
  'adminDeactivateTailor' : IDL.Func([Id], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([Id], [], []),
  'createBooking' : IDL.Func([IDL.Text, IDL.Int, IDL.Opt(Id)], [Id], []),
  'createTailorProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Id], []),
  'deleteSavedAddress' : IDL.Func([Id], [], []),
  'getAllBookings' : IDL.Func(
      [BookingSortColumn, BookingSortDirection],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getAllTailorProfiles' : IDL.Func([], [IDL.Vec(TailorProfile)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBooking' : IDL.Func([Id], [IDL.Opt(Booking)], ['query']),
  'getBookingHistory' : IDL.Func([Id], [IDL.Opt(BookingHistory)], ['query']),
  'getBookingStatus' : IDL.Func([Id], [BookingStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMySavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
  'getMyTailorBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyTailorProfile' : IDL.Func([], [IDL.Opt(TailorProfile)], ['query']),
  'getTailorProfile' : IDL.Func([Id], [IDL.Opt(TailorProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAddress' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEstimatedPrice' : IDL.Func([Id, IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([Id, BookingStatus], [], []),
  'updatePaymentStatus' : IDL.Func([Id, PaymentStatus], [], []),
  'updateTailorProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingSortColumn = IDL.Variant({
    'customerPrincipal' : IDL.Null,
    'tailorName' : IDL.Null,
    'bookingDate' : IDL.Null,
  });
  const BookingSortDirection = IDL.Variant({
    'asc' : IDL.Null,
    'desc' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : Id,
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'customer' : IDL.Principal,
    'estimatedPrice' : IDL.Opt(IDL.Nat),
    'tailor' : IDL.Opt(IDL.Principal),
    'address' : IDL.Text,
    'dateTime' : IDL.Int,
  });
  const TailorProfile = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const BookingHistory = IDL.Record({
    'bookingId' : Id,
    'statusLog' : IDL.Vec(IDL.Tuple(BookingStatus, IDL.Int)),
  });
  const SavedAddress = IDL.Record({
    'id' : Id,
    'owner' : IDL.Principal,
    'addressLabel' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBooking' : IDL.Func([Id], [], []),
    'adminActivateTailor' : IDL.Func([Id], [], []),
    'adminAssignTailorToBooking' : IDL.Func([Id, Id], [], []),
    'adminDeactivateTailor' : IDL.Func([Id], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([Id], [], []),
    'createBooking' : IDL.Func([IDL.Text, IDL.Int, IDL.Opt(Id)], [Id], []),
    'createTailorProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Id], []),
    'deleteSavedAddress' : IDL.Func([Id], [], []),
    'getAllBookings' : IDL.Func(
        [BookingSortColumn, BookingSortDirection],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllTailorProfiles' : IDL.Func([], [IDL.Vec(TailorProfile)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBooking' : IDL.Func([Id], [IDL.Opt(Booking)], ['query']),
    'getBookingHistory' : IDL.Func([Id], [IDL.Opt(BookingHistory)], ['query']),
    'getBookingStatus' : IDL.Func([Id], [BookingStatus], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMySavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
    'getMyTailorBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyTailorProfile' : IDL.Func([], [IDL.Opt(TailorProfile)], ['query']),
    'getTailorProfile' : IDL.Func([Id], [IDL.Opt(TailorProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAddress' : IDL.Func([IDL.Text, IDL.Text], [Id], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEstimatedPrice' : IDL.Func([Id, IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([Id, BookingStatus], [], []),
    'updatePaymentStatus' : IDL.Func([Id, PaymentStatus], [], []),
    'updateTailorProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };