/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : Id,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'customer' : Principal,
  'estimatedPrice' : [] | [bigint],
  'tailor' : [] | [Principal],
  'address' : string,
  'dateTime' : bigint,
}
export interface BookingHistory {
  'bookingId' : Id,
  'statusLog' : Array<[BookingStatus, bigint]>,
}
export type BookingSortColumn = { 'customerPrincipal' : null } |
  { 'tailorName' : null } |
  { 'bookingDate' : null };
export type BookingSortDirection = { 'asc' : null } |
  { 'desc' : null };
export type BookingStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type Id = bigint;
export type PaymentStatus = { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null };
export interface SavedAddress {
  'id' : Id,
  'owner' : Principal,
  'addressLabel' : string,
  'address' : string,
}
export interface TailorProfile {
  'id' : Id,
  'bio' : string,
  'owner' : Principal,
  'name' : string,
  'isActive' : boolean,
  'address' : string,
  'rating' : [] | [bigint],
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBooking' : ActorMethod<[Id], undefined>,
  'adminActivateTailor' : ActorMethod<[Id], undefined>,
  'adminAssignTailorToBooking' : ActorMethod<[Id, Id], undefined>,
  'adminDeactivateTailor' : ActorMethod<[Id], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[Id], undefined>,
  'createBooking' : ActorMethod<[string, bigint, [] | [Id]], Id>,
  'createTailorProfile' : ActorMethod<[string, string, string], Id>,
  'deleteSavedAddress' : ActorMethod<[Id], undefined>,
  'getAllBookings' : ActorMethod<
    [BookingSortColumn, BookingSortDirection],
    Array<Booking>
  >,
  'getAllTailorProfiles' : ActorMethod<[], Array<TailorProfile>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBooking' : ActorMethod<[Id], [] | [Booking]>,
  'getBookingHistory' : ActorMethod<[Id], [] | [BookingHistory]>,
  'getBookingStatus' : ActorMethod<[Id], BookingStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyCustomerBookings' : ActorMethod<[], Array<Booking>>,
  'getMySavedAddresses' : ActorMethod<[], Array<SavedAddress>>,
  'getMyTailorBookings' : ActorMethod<[], Array<Booking>>,
  'getMyTailorProfile' : ActorMethod<[], [] | [TailorProfile]>,
  'getTailorProfile' : ActorMethod<[Id], [] | [TailorProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAddress' : ActorMethod<[string, string], Id>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEstimatedPrice' : ActorMethod<[Id, bigint], undefined>,
  'updateBookingStatus' : ActorMethod<[Id, BookingStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[Id, PaymentStatus], undefined>,
  'updateTailorProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];